### ISSUE TITLE
DEPLOYMENT FAILED

### ISSUE THREAD

**Issue by r7deku** [itsyogieu/TechMagazine-AutoFilterBot#3]
Bot one started after some time it automatically stopped. it showing error
screenshot https://drive.google.com/file/d/1M_L6p8AlqJS1jOqF-aDp2Bm2wqq9nN_Y/view?usp=sharing

**Comment by r7deku** [comment]
bro pls give reply

**Comment by itsyogieu** [comment]
I will check and fix it ji

**Comment by itsyogieu** [comment]
> Bot one started after some time it automatically stopped. it showing error screenshot https://drive.google.com/file/d/1M_L6p8AlqJS1jOqF-aDp2Bm2wqq9nN_Y/view?usp=sharing

I will check and fix it ji

**Comment by itsyogieu** [comment]
> > Bot one started after some time it automatically stopped. it showing error screenshot https://drive.google.com/file/d/1M_L6p8AlqJS1jOqF-aDp2Bm2wqq9nN_Y/view?usp=sharing
> 
> I will check and fix it ji

![20230215_225447](https://user-images.githubusercontent.com/82885288/219105952-29e94190-0eec-40a2-b696-74fc0e66e58d.jpg)
